### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by E-Kirill** [seredat/karbowanec#10]
build error on macOS
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   chrono
--   regex
--   serialization
--   program_options
--   atomic
-- Found Git: /usr/bin/git
CMake Warning in CMakeLists.txt:
  CMAKE_SKIP_INSTALL_RULES was enabled even though installation rules have
  been specified

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/kirill/Projects/karbowanec/build/release
cd build/release && /Applications/Xcode.app/Contents/Developer/usr/bin/make
[  0%] Built target version
[  5%] Built target upnpc-static
[  6%] Built target gtest
[  6%] Built target gtest_main
[ 13%] Built target Common
[ 14%] Built target BlockchainExplorer
[ 17%] Built target Serialization
[ 17%] Building C object src/CMakeFiles/System.dir/Platform/OSX/System/Context.c.o
/Users/kirill/Projects/karbowanec/src/Platform/OSX/System/Context.c:19:10: error: non-portable path to file '"Context.h"'; specified path differs in case from file name on disk
      [-Werror,-Wnonportable-include-path]
#include "context.h"
         ^~~~~~~~~~~
         "Context.h"
In file included from /Users/kirill/Projects/karbowanec/src/Platform/OSX/System/Context.c:19:
/Users/kirill/Projects/karbowanec/src/Platform/OSX/System/context.h:32:40: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
extern  void            makecontext(uctx*, void(*)(), intptr_t);
                                                  ^
                                                   void
2 errors generated.
make[3]: *** [src/CMakeFiles/System.dir/Platform/OSX/System/Context.c.o] Error 1
make[2]: *** [src/CMakeFiles/System.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [build-release] Error 2

**Comment by zhmrab** [comment]
I have the same problem as well, anyone found a solution to this yet?

**Comment by aivve** [comment]
Please pull and try again, I suppose it's wrong filename case in `#include "context.h"`

**Comment by zhmrab** [comment]
Ok thanks for the tip aivve! I just tried and now I'm getting this! 
Have you seen this before?

src/Platform/OSX/System/context.h:19:40: error: this
      function declaration is not a prototype [-Werror,-Wstrict-prototypes]
extern  void            makecontext(uctx*, void(*)(), intptr_t);

**Comment by aivve** [comment]
Hm, why context.h is in lower case? Should be Context.h

**Comment by zhmrab** [comment]
It is in uppercase in my folder as Context.h but comes out like this in the terminal, I just tried 
make -j4 again and I'm still getting this : 

Ps : thanks for taking the time to respond, I am trying to sort this out for a charity project I am working on!

/Users/Crypto/testcoin/src/Platform/OSX/System/Context.c:6:10: error: non-portable path to file '"Context.h"'; specified path differs in case from file name on disk
      [-Werror,-Wnonportable-include-path]
#include "context.h"
         ^~~~~~~~~~~
         "Context.h"
In file included from /Users/Crypto/testcoin/src/Platform/OSX/System/Context.c:6:
/Users/Crypto/afrika/src/Platform/OSX/System/context.h:19:40: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
extern  void            makecontext(uctx*, void(*)(), intptr_t);
                                                  ^
                                                   void

**Comment by zhmrab** [comment]
Had to fix context.h and context.c with with caps & void argument missing.. All good now

**Comment by mbellamy** [comment]
@zhmrab what do you mean fix with cap & void argument missing?

**Comment by E-Kirill** [comment]
@aivve 
Hello, now Im getting this error:
<img width="1440" alt="2018-01-15 11 07 17" src="https://user-images.githubusercontent.com/24874326/34934774-6c310b9e-f9e4-11e7-9cb5-6e460aab0ce2.png">

**Comment by aivve** [comment]
Are you trying to build fo iOS? Try turn off warning `-Wstrict-prototypes` or try change that line this way: ```extern	void		makecontext(uctx*, void(*)(void), intptr_t);```. I don't have access tp Xcode to check.

**Comment by timk14** [comment]
hey @aivve I am having the same issue.. Can you explain how to turn off that warning?? Also I cant find the code that the error is referencing. It says in Context.h 19:41 but when i go to line 19 this " bindingContext.interrupted = false;" is what is there.. I cant find that code anywhere..

**Comment by aivve** [comment]
Should be fixed by https://github.com/seredat/karbowanec/commit/5ac6c6a3bad820630ae948be34e342b3ed19502d

**Comment by driquelme** [comment]
> Are you trying to build fo iOS? Try turn off warning `-Wstrict-prototypes` or try change that line this way: `extern void makecontext(uctx*, void(*)(void), intptr_t);`. I don't have access tp Xcode to check.

Is it possible to build for iOS? How can I do that?

**Comment by aivve** [comment]
It should be possible to build for iOS, but what for? They won't allow you to run that on their precious walled garden.
