### ISSUE TITLE
CPU load high

### ISSUE THREAD

**Issue by sebseb7** [seredat/karbowanec#13]
karbowanecd consumes 1 full CPU on Xeon 8 Core system.

Multiple cryptonote daemons running on that system, only karbo takes so much load. Is the CPU Miner running accidentally?

https://imgur.com/a/76Kqx

**Comment by aivve** [comment]
Is it open to the world as node for lite wallets?

**Comment by sebseb7** [comment]
the system has public ip no firewall, started using "--no-console --enable-blockchain-indexes"

**Comment by aivve** [comment]
Add these paramenters, please: `./karbowanecd --restricted-rpc --enable-cors=* --enable-blockchain-indexes --rpc-bind-port=32348 --rpc-bind-ip=0.0.0.0` just in case
It's unlikely that some one abused it with mining, it might be some lite wallet connected to your node (have you published it anywhere?) but it's also unlikely.
Is it fully synchronized? It may consume cpu while synchronizing or processing really large transaction, it't temporarily in this case.

**Comment by sebseb7** [comment]
I have closed any external port, no miner is conneted as well, it's fully synced as well, still CPU load is very high, about 50%

**Comment by aivve** [comment]
Have you tried to restart it?

**Comment by sebseb7** [comment]
I have all external ports blocked now and load is still very high, do you have discord to figure that out?

btw: it's debian 9, but with boost 1.58 because cryotnotepool doesn't like boost 1.62

**Comment by aivve** [comment]
Telegram chat https://t.me/karbo_en
