### ISSUE TITLE
Karbowabec 1.7.7 win64 and higher need two additional dlls

### ISSUE THREAD

**Issue by parmax** [seredat/karbowanec#149]
When i tried to run simplewalet.exe but alerts show me "didn't found libcrypto-1_1-x64__.dll and libssl-1_1-x64__.dll"
Where find i this?

**Comment by aivve** [comment]
Um, this must be a problem with compiled version, shouldn't have required ddls.

**Comment by parmax** [comment]
Где взяты ці dll, чи як встановити. Тощо.

**Comment by aivve** [comment]
Гадаю можна просто встановити OpenSSL але це не вихід, спробуємо переробити так аби дллки не вимагались.

**Comment by parmax** [comment]
В том и вопрос что установкой стандартной OpenSSL 1.1 x64 это не полечилось ибо требует либы 1-1_x64__.dll, а установкой оного устанавливаются 1_1-x64.dll

**Comment by aivve** [comment]
Can you try https://github.com/seredat/karbowanec/suites/2986146730/artifacts/67408282  ?
