### ISSUE TITLE
v.1.4.6 - Win10x64 - simplewallet.exe Crashing while attempting to Generate wallet

### ISSUE THREAD

**Issue by semtex41** [seredat/karbowanec#16]
Here is the event from eventviewer:
Faulting application name: simplewallet.exe, version: 0.0.0.0, time stamp: 0x5a5b66be
Faulting module name: simplewallet.exe, version: 0.0.0.0, time stamp: 0x5a5b66be
Exception code: 0xc0000409
Fault offset: 0x0000000000189afc
Faulting process id: 0x1308
Faulting application start time: 0x01d38dca883de98f
Faulting application path: *****\Karbo-cli-1.4.6-win-64-bit\karbo\simplewallet.exe
Faulting module path: *****\Karbo-cli-1.4.6-win-64-bit\karbo\simplewallet.exe
Report Id: 627cb8fa-29d4-42e0-9ebc-b335ad51e246
Faulting package full name: 
Faulting package-relative application ID:

**Comment by aivve** [comment]
Are you running daemon karbowanecd first?

**Comment by aivve** [comment]
Should be fixed by  https://github.com/seredat/karbowanec/commit/01d6b642cf90cfce7d077504d29538b9942a2b14
