### ISSUE TITLE
Random crash in miner

### ISSUE THREAD

**Issue by KarboDuck** [seredat/karbowanec#172]
![photo_2022-01-08_18-04-00](https://user-images.githubusercontent.com/53382906/148651302-d73ff5f6-192f-403e-969e-df9850d144a0.jpg)

Windows 11, Ryzen 5800x, karbowanecd 1.9.5.

Relevant part of log, though nothing interesting there
[krb.txt](https://github.com/seredat/karbowanec/files/7833533/krb.txt)

**Comment by aivve** [comment]
Should be fixed in https://github.com/seredat/karbowanec/pull/193
