### ISSUE TITLE
Change minimum fee?

### ISSUE THREAD

**Issue by devpacito** [seredat/karbowanec#20]
Hello, 

I tried to build from source and all went perfectly but when I change the minimum_fee, eg becomes 0.001 (1000000000) instead of 0.0001 (100000000) than weird things happens, let say I sent 1 KRB using the GUI Wallet (Windows 10) than it count if I sent 10 KRB (balance reduced by 10 KRB). When using the console it work as expected .

Is there any hardcoded value for this behavior?

Thanks,

**Comment by aivve** [comment]
Why would you need to change this? And where are you doing this?

**Comment by devpacito** [comment]
@aivve I want to learn about creating a cryptocurrency and using Karbo code as base (v.1.4.4). I change the [CryptoNoteConfig.h](https://github.com/seredat/karbowanec/blob/master/src/CryptoNoteConfig.h) value like the seed nodes, genesis coinbase etc. than build it (CLI, Wallet).

**Comment by devpacito** [comment]
Seems using the default minimum fees also have similar behavior. Try to solo mining using my own setup (Heigh still below 20) and it send 10 instead of 1.
