### ISSUE TITLE
Warning ! You must put copyright issue notice if you want use new difficulty algo.

### ISSUE THREAD

**Issue by bobbieltd** [seredat/karbowanec#27]
I love new and improved codes. But I feel annoyed the way of new difficulty algo moving around and I doubt their motives. I think what they do is not to help others (still unconfirmed improvements) but to put their copyright at Readme of other projects.
You MUST put “Portions Copyright 2017 Masari Project” at Readme and in difficulty.cpp for just some lines of codes which I’m not sure they are effective. It’s not worth it.
In the worst case, if you are careless, they can file a DCMA to put your repo down.

**Comment by aivve** [comment]
LOL. WE WERE THE FIRST CURRENCY TO IMPLEMENT THIS ALGO BACK IN 2016. IT IS MASASI HAS TO CREDIT US.

**Comment by bobbieltd** [comment]
I just realised that I could misunderstand something here. Overangry brought me misinformation.

**Comment by zawy12** [comment]
Masari is using [my newest algorithm](https://github.com/zawy12/difficulty-algorithms/issues/3).  There is another coin that copied their code and I've notified @thaer.

**Comment by aivve** [comment]
Yes. The copyright and credits must be attributed to zawy12 in fact. If we decide to update to that algo, we will credit it's author.
