### ISSUE TITLE
Big Transaction Issue in Karbo Network

### ISSUE THREAD

**Issue by albertalbs** [seredat/karbowanec#28]
Hello, 

I was trying pool mining at http://pool.karbowanec.com/
Mined payment initiated on 2/10/2018, 1:21:44 AM to my desktop wallet address : KejSatFcubB6AvLbiYwtbpcyM1pVWfph8AcsX3fUPEUEKdXcwQWSdnuSzEYrBS1jHVLUn4pbZNiPHhYs2CKmieHfMNFszAs

But till date that payment did not arrive in my desktop wallet. My desktop wallet is fully synced with karbo blockchain. 
Screenshot: 
![screenshot-pool karbowanec com-2018 03 10-14-29-30](https://user-images.githubusercontent.com/608213/37240309-9c5e80ac-246f-11e8-832c-5115eb80984a.png)

**My wallet address:** KejSatFcubB6AvLbiYwtbpcyM1pVWfph8AcsX3fUPEUEKdXcwQWSdnuSzEYrBS1jHVLUn4pbZNiPHhYs2CKmieHfMNFszAs

**Transaction Hash:** 8b240770608e8f7e8aac601279b87667c4b05c2bd03ed1a32b171daf858ac30d

**Please help.**

**Comment by albertalbs** [comment]
Pool payment proof:
![screenshot-pool karbowanec com-2018 03 10-14-35-31](https://user-images.githubusercontent.com/608213/37240380-69b606ec-2470-11e8-9764-49e30ffd0f8a.png)

**Comment by aivve** [comment]
Choose different node in connection settings, as you can see in status bar, the height is zero - you're not synced. A list of available nodes is, for example, here http://www.karbo.cloud/ click on marker on the map and copy IP, or look for nodes announcements on our bitcointalk thread https://bitcointalk.org/index.php?topic=1491747.new#new

**Comment by albertalbs** [comment]
@aivve Ok. Now I have received the KRB in desktop wallet. 

But I've imported the same wallet in Android walled with mnemonic seed. But the balance is not reflecting in there.

**Comment by aivve** [comment]
You need no wait, importing from seed takes some time.

**Comment by albertalbs** [comment]
Ok. Start providing incentive for master nodes and also enable master node feature in Desktop wallet. 
From India, My IP is showing as master node in that Master nodes Network map: http://www.karbo.cloud/

**Comment by aivve** [comment]
The map should be fixed by now.
