### ISSUE TITLE
Cryptonote difficulty adjustment algo against multipool effect

### ISSUE THREAD

**Issue by aivve** [seredat/karbowanec#3]
You can observe nice 'multipool effect' on Cryptonote fork Karbowanec 
http://democats.org/charts/?name=karbowanec&type=basic
big miner comes, mines easy blocks and suddenly drops when difficulty increases leaving network with big delays between blocks.

@zawy12, there is occasion to test your difficulty algo on live Cryptonote coin.

**Comment by seredat** [comment]
We hope to fix it in this release.

**Comment by seredat** [comment]
Useful comments concerning difficulty algo are here:  https://github.com/seredat/karbowanec/commit/231db5270acb2e673a641a1800be910ce345668a
