### ISSUE TITLE
getblockcount - JsonValue type is not ARRAY or OBJECT

### ISSUE THREAD

**Issue by easyhash** [seredat/karbowanec#30]
When trying to retrieve getblockcount from the Linux daemon RPC interface, i get `JsonValue type is not ARRAY or OBJECT`

```
curl -X POST http://daemon:19734/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getblockcount"}' -H 'Content-Type: application/json'
{"error":{"code":-32603,"message":"JsonValue type is not ARRAY or OBJECT"},"id":"0","jsonrpc":"2.0"}
```

**Comment by zawy12** [comment]
I had a similar problem.  Karbo has an extra requirement that other monero's don't.  Try inserting ```"params": {},``` like this:

```curl -X POST http://daemon:19734/json_rpc -d '{"params": {}, "jsonrpc":"2.0","id":"0","method":"getblockcount"}' -H 'Content-Type: application/json'```
