### ISSUE TITLE
Double assignment to parent block majorVersion

### ISSUE THREAD

**Issue by helder-garcia** [seredat/karbowanec#31]
On Core.cpp, function core::get_block_template we have a double assignment to the same attribute:
      b.parentBlock.majorVersion = BLOCK_MAJOR_VERSION_1;
      b.parentBlock.majorVersion = BLOCK_MINOR_VERSION_0;
Do you think it should be like this?
      b.parentBlock.majorVersion = BLOCK_MAJOR_VERSION_1;
      b.parentBlock.minorVersion = BLOCK_MINOR_VERSION_0;

If so, are you able to estimate the impact of changing it on a running blockchain?

**Comment by aivve** [comment]
Yes, it's an error I think and honestly I don't know will it impact. Probably not. 

Update: probably not error as it's still in papa's code:
https://github.com/amjuarez/bytecoin/blob/master/src/CryptoNoteCore/Core.cpp#L1021 or they haven't noticed this 😆

**Comment by helder-garcia** [comment]
kkk probably they don't. It doesn't make sense!

**Comment by aivve** [comment]
https://github.com/seredat/karbowanec/blob/master/src/CryptoNoteCore/Core.cpp#L371

**Comment by aivve** [comment]
No more parent block and merged mining for Karbo
