### ISSUE TITLE
Karbowanec.exe crashing repeteadly. 

### ISSUE THREAD

**Issue by pr0b3r7** [seredat/karbowanec#33]
Hi Karbo team!,

Thank you for your efforts so far with Karbo. I am having some issues with your wallet app though. Please find below the event viewer log for the latest crash. Let me know if you need any more information on my system. 

Faulting application name: karbowanec.exe, version: 1.0.0.5, time stamp: 0x5a88acd6
Faulting module name: karbowanec.exe, version: 1.0.0.5, time stamp: 0x5a88acd6
Exception code: 0xc0000005
Fault offset: 0x000e1953
Faulting process id: 0x1b60
Faulting application start time: 0x01d3c6c625e7ccf6
Faulting application path: C:\Program Files (x86)\Karbowanec\karbowanec.exe
Faulting module path: C:\Program Files (x86)\Karbowanec\karbowanec.exe
Report Id: e5e3e787-34b6-4839-a609-b38eb12268e0
Faulting package full name: 
Faulting package-relative application ID:

**Comment by pr0b3r7** [comment]
Log Name:      Application
Source:        Application Error
Date:          3/29/2018 12:10:22 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-JC8R0N7
Description:
Faulting application name: karbowanec.exe, version: 1.0.0.5, time stamp: 0x5a88acd6
Faulting module name: karbowanec.exe, version: 1.0.0.5, time stamp: 0x5a88acd6
Exception code: 0xc0000005
Fault offset: 0x000e1953
Faulting process id: 0x117c
Faulting application start time: 0x01d3c776addcc09c
Faulting application path: C:\Program Files (x86)\Karbowanec\karbowanec.exe
Faulting module path: C:\Program Files (x86)\Karbowanec\karbowanec.exe
Report Id: a9ecf53c-2ac0-4c3d-9115-adc42fa48d27
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-03-29T16:10:22.919871300Z" />
    <EventRecordID>37566</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-JC8R0N7</Computer>
    <Security />
  </System>
  <EventData>
    <Data>karbowanec.exe</Data>
    <Data>1.0.0.5</Data>
    <Data>5a88acd6</Data>
    <Data>karbowanec.exe</Data>
    <Data>1.0.0.5</Data>
    <Data>5a88acd6</Data>
    <Data>c0000005</Data>
    <Data>000e1953</Data>
    <Data>117c</Data>
    <Data>01d3c776addcc09c</Data>
    <Data>C:\Program Files (x86)\Karbowanec\karbowanec.exe</Data>
    <Data>C:\Program Files (x86)\Karbowanec\karbowanec.exe</Data>
    <Data>a9ecf53c-2ac0-4c3d-9115-adc42fa48d27</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Todays crash after 15 min usage of wallet.

**Comment by pr0b3r7** [comment]
Anyone? Is there any more information I can gather to aid in the diagnosis of this problem?
Thanks

**Comment by aivve** [comment]
This particular issue I suppose was due to unusual and hard to verify transactions with the enormous number of mixins on which some wallets were crashing trying to verify them. Should not repeat again after the https://github.com/seredat/karbowanec/commit/c11f09e23353f0a763682eadb43f686e7550438e
