### ISSUE TITLE
Compile error under windows LNK2001 LNK2019

### ISSUE THREAD

**Issue by ghost** [seredat/karbowanec#38]
Hello i wanted to compile latest version of karbowanec ( with : Visual Studio 2017 Enterprise , CMAKE 3.10.0 , Boost 1_65_1 , Windows 8.1 Enterprise) but i got following errors : 
5>miniupnpc.lib(miniupnpc.obj) : error LNK2019: unresolved external symbol __imp__memicmp referenced in function upnpDiscover
25>miniupnpc.lib(miniwget.obj) : error LNK2001: unresolved external symbol __imp__memicmp
25>miniupnpc.lib(miniupnpc.obj) : error LNK2019: unresolved external symbol __imp__strdup referenced in function GetUPNPUrls
25>miniupnpc.lib(upnpreplyparse.obj) : error LNK2001: unresolved external symbol __imp_strncpy
25>miniupnpc.lib(miniupnpc.obj) : error LNK2001: unresolved external symbol __imp_strncpy
25>miniupnpc.lib(upnpcommands.obj) : error LNK2001: unresolved external symbol __imp_strncpy
25>miniupnpc.lib(miniwget.obj) : error LNK2001: unresolved external symbol __imp_strncpy
25>miniupnpc.lib(connecthostport.obj) : error LNK2001: unresolved external symbol __imp_strncpy
25>miniupnpc.lib(miniwget.obj) : error LNK2019: unresolved external symbol __imp_perror referenced in function miniwget2
25>miniupnpc.lib(miniwget.obj) : error LNK2019: unresolved external symbol __imp_realloc referenced in function getHTTPResponse
25>C:\Users\Anon\Desktop\karbowanec\build\src\Release\walletd.exe : fatal error LNK1120: 5 unresolved externals
25>Done building project "PaymentGateService.vcxproj" -- FAILED.
26>SimpleWallet.vcxproj -> C:\Users\Anon\Desktop\karbowanec\build\src\Release\simplewallet.exe
27>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
========== Build: 23 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========

**Comment by aivve** [comment]
In VS' Solution Explorer select upnpc-static' Properies -> C/C++ -> Code Generation -> Runtime Library - > change it to Multi-threaded (/MT)

**Comment by ghost** [comment]
thank you @aivve  your solution worked just fine.
