### ISSUE TITLE
Building for android problem with libboost

### ISSUE THREAD

**Issue by ghost** [seredat/karbowanec#39]
hello i did everything as is on readme file but i got following error : 

CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/include

  Could not find the following static Boost libraries:

          boost_system
          boost_filesystem
          boost_thread
          boost_date_time
          boost_chrono
          boost_regex
          boost_serialization
          boost_program_options
          boost_coroutine
          boost_context
          boost_atomic

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:489 (find_package)

CMake Error at CMakeLists.txt:493 (die):
  Unknown CMake command "die".

CMake Warning in CMakeLists.txt:
  CMAKE_SKIP_INSTALL_RULES was enabled even though installation rules have
  been specified

-- Configuring incomplete, errors occurred!

what should i do ?

**Comment by brovko** [comment]
You have to have static boost libraries like libboost_system.a. Maybe you should compile and install boost from sources.
