### ISSUE TITLE
compiler error: value-initialization of incomplete type

### ISSUE THREAD

**Issue by JollyMort** [seredat/karbowanec#4]
Hi,

I'm getting this error when running `make`, any ideas? (Arch linux x64 gcc (GCC) 6.3.1 20170306)

    karbowanec/src/crypto/crypto.cpp:350:58: error: value-initialization of incomplete type 
    ‘Crypto::rs_comm::<anonymous struct> []’
         return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);

**Comment by JollyMort** [comment]
gonna try applying this patch: https://github.com/monero-project/monero/commit/6462a3a6db8452523b8c07d8394fbc5dc86f7295

**Comment by JollyMort** [comment]
ok that fixed it (modified a little for variable names):

	diff --git a/src/crypto/crypto.cpp b/src/crypto/crypto.cpp
	index b5f2b99..0dc4e98 100644
	--- a/src/crypto/crypto.cpp
	+++ b/src/crypto/crypto.cpp
	@@ -339,15 +339,17 @@ namespace Crypto {
	 #pragma warning(disable: 4200)
	 #endif

	+  struct ec_point_pair {
	+    EllipticCurvePoint a, b;
	+  };
	+
	   struct rs_comm {
		 Hash h;
	-    struct {
	-      EllipticCurvePoint a, b;
	-    } ab[];
	+       struct ec_point_pair ab[];
	   };

	   static inline size_t rs_comm_size(size_t pubs_count) {
	-    return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
	+    return sizeof(rs_comm) + pubs_count * sizeof(ec_point_pair);
	   }

	   void crypto_ops::generate_ring_signature(const Hash &prefix_hash, const KeyImage &image,


but now getting this:

	/src/crypto/slow-hash.cpp: In destructor ‘Crypto::cn_context::~cn_context()’:
	/src/crypto/slow-hash.cpp:67:23: error: throw will always call terminate() [-Werror=terminate]
		   throw bad_alloc();
						   ^
	/src/crypto/slow-hash.cpp:67:23: note: in C++11 destructors default to noexcept

**Comment by JollyMort** [comment]
found [this](https://github.com/monero-project/monero/issues/834), gonna try and fix

**Comment by aivve** [comment]
Any success with this?

**Comment by JollyMort** [comment]
Nope, sorry - I was poking around and didn't manage to figure it out and just went with release binaries. I lack the skills to pursue this further without spending days at it. Problem is, I have all packages up to date, so now having some build issues with Monero as well, due to Boost 1.64. At least it builds, but some tests fail.

**Comment by aivve** [comment]
I see, thank you for the info. I assume release binaries are working, they should as they are static.

**Comment by JollyMort** [comment]
Yup, those work. Cheers! PS "Dune" was an awesome game :)

**Comment by vkobel** [comment]
Pull request #42 is dealing with this issue :)
