### ISSUE TITLE
Memory leak fix

### ISSUE THREAD

**Issue by momchilmg** [seredat/karbowanec#41]
file : src/crypto/slow-hash.c

line 479 : VirtualFree(hp_state, MEMORY, MEM_RELEASE);

The correct expression is : VirtualFree(hp_state, 0, MEM_RELEASE);

I have 24GB RAM and this wallet get 95% without this fix.

More info here : https://msdn.microsoft.com/en-us/library/windows/desktop/aa366892(v=vs.85).aspx

"If you specify this value, dwSize must be 0 (zero), and lpAddress must point to the base address returned by the VirtualAlloc function when the region is reserved. The function fails if either of these conditions is not met."

Thanks! :)

**Comment by aivve** [comment]
Thanks! Would you like to make pull request?

**Comment by momchilmg** [comment]
Sorry, but I'm busy right now. You can add this change ;) Thanks for your proposition!

Your project is great. We will use your code in our project. We respect GPL licence and your work has been respected. :) This is beta version for now - http://blablahost.net/Levcoincash-1.0.3.exe

**Comment by aivve** [comment]
It's not urgent. We will review and commit it for next update. Thanks again.

**Comment by aivve** [comment]
Confirmed.

```
Incorrect Size parameter for VirtualFree (MEM_RELEASE) operation.
200000 - Incorrect size used by the application.
0 - Expected correct size (0).
```

**Comment by momchilmg** [comment]
Two beta testers confirm the fix and hashrate is increase too.

**Comment by aivve** [comment]
Need to check memory usage more.

**Comment by momchilmg** [comment]
Yes, but this is very hard work ;) For now I think this is enough.
