### ISSUE TITLE
Maybe one wrong line ?

### ISSUE THREAD

**Issue by momchilmg** [seredat/karbowanec#44]
file src/CryptoNoteCore/Core.cpp

line 417 : b.parentBlock.majorVersion = BLOCK_MINOR_VERSION_0;

Maybe the correct line is b.parentBlock.**minor**Version = BLOCK_MINOR_VERSION_0; ?

How I can contact Karbo Dev team? Personal email?  I have one business offer. ;) Thanks!

**Comment by aivve** [comment]
No, it's related to merged mining and it's totally messed up without logic. We got it as legacy from ByteCoin. Unfortunately I missed it before it was too late to get rid of this.

Find me on Telegram https://t.me/Aivve or mail us to krbcoin@ukr.net

**Comment by aivve** [comment]
Got rid of merged mining in https://github.com/seredat/karbowanec/releases/tag/v.1.5.3 and next updates
