### ISSUE TITLE
question about wallet!

### ISSUE THREAD

**Issue by systemroot** [seredat/karbowanec#5]
hello

i was running a pool and mining solo. i got some KRB's and now example how can i transfer my KRB's to some wallet?!

as i was running as solo i generated a wallet with ./walletd
but i can't find any doc about how to transfer :/ and if i wrote "help" in cli console i doesn't give any info about this :confused: 
![](http://i.imgur.com/ptfhP2U.png)

can i have some help? thanks.

EDIT: 
i tried simplewallet i'm getting this error
```bash
2017-Jun-09 05:00:25.251455 ERROR   Wallet initialize failed: can't load wallet file 'theraw.wallet', check password
^[^C
```

after that now when i tried to turn on again "walletd" i'm getting this error 
```bash
2017-Jun-09 05:03:26.471999 ERROR   Unsupported wallet version: 75
2017-Jun-09 05:03:26.472713 ERROR   Failed to init walletService reason: Unsupported wallet version: Wrong version
```

**Comment by seredat** [comment]
walletd uses different type of wallet, it can't be opened in simplewallet. To transfer coins you have to send json prc command because walletd is intended to be used in services. Example how to transfer is in [Wiki tab](https://github.com/seredat/karbowanec/wiki/RPC-Wallet-API#Send_transaction)

**Comment by systemroot** [comment]
@seredat thank you for info!
can you please give a simple example of how can i do curl api request for transaction?!

**Comment by seredat** [comment]
something like this:

`curl -X POST -i -H "Accept: application/json" -d '{ "params":{"anonymity":0,"fee":100000000,"unlockTime":0,"paymentId":"","addresses":["KbzvFzjQeWCZawinhkDZUKF6pjDv1TLU678poSAEFKWRL3kgWk48sxCN8z6tpfkzMZ82AQyfhiU4uZ66mnU942AHKokr6PG"],"transfers":[{"amount":25000000000000,"address":"KbjVbfZkw5eYMMBBYCEoc3TtMe6yNQgPvSepH1KRqxhc3Pr2VBtFLrtD1E6oQAEbtJQsbJrtqWjMoKo1q5HtKAFdUcYBH41"}],"changeAddress":"KbzvFzjQeWCZawinhkDZUKF6pjDv1TLU678poSAEFKWRL3kgWk48sxCN8z6tpfkzMZ82AQyfhiU4uZ66mnU942AHKokr6PG"},"jsonrpc":"2.0","id":"test","method":"sendTransaction"}' http://127.0.0.1:32348/json_rpc`

you can also use getViewKey() and getSpendKeys() methods to export your keys for specific address and import them in simplewallet

**Comment by systemroot** [comment]
"`Connection refused`"
and i'm not able to turn on walletd
```
2017-Jun-09 06:35:31.826085 INFO    walletd v1.4.3.708 (ce804fa)
2017-Jun-09 06:35:31.826349 INFO    Starting Payment Gate with remote node
2017-Jun-09 06:35:31.826659 INFO    Loading wallet
2017-Jun-09 06:35:31.826738 INFO    Loading container...
2017-Jun-09 06:35:31.857288 ERROR   Unsupported wallet version: 75
2017-Jun-09 06:35:31.857863 ERROR   Failed to init walletService reason: Unsupported wallet version: Wrong version
2017-Jun-09 06:35:31.857946 INFO    Stopping...
2017-Jun-09 06:35:31.858006 INFO    Stopped
2017-Jun-09 06:35:31.858059 INFO    Stopping...
2017-Jun-09 06:35:31.858112 INFO    Stopped
```
i think i've done something wrong.. and i'll start from beginning!
if u know how to solve this tell me and send me your wallet code i'll send those as donate to you..

**Comment by seredat** [comment]
Hm, try to open it in walletd version you used to create wallet container, and use abovementioned getViewKey() and getSpendKeys() methods to export your private keys, then you will be able to import them into simplewallet

**Comment by systemroot** [comment]
@seredat i deleted all old cli and i tried to open again karbowanecd to turn daemon on i'm getting this output
![](http://i.imgur.com/l4p3baQ.png)
is this normal?

**Comment by seredat** [comment]
Those connections are from nodes that did not updated and are on Karbowanec Classic network :)

**Comment by systemroot** [comment]
which means nothing to worry about? or should i do anything about it!?

**Comment by seredat** [comment]
Don't worry about these messages.

**Comment by systemroot** [comment]
thank you for support

**Comment by systemroot** [comment]
@seredat a question out of this pr.

as i know only livecoins support krb?! does it work? i've send some krb on that but i can't see them on dashboard also their support doesn't reply to my ticket :confused:

**Comment by seredat** [comment]
There is forum on BTT https://bitcointalk.org/index.php?topic=1491747.new#new

**Comment by systemroot** [comment]
@seredat hi again!!

is there anyway how to set a limit for daemon, it's using 500% of disk I/O and it's getting **killed** and i can't sync blockchain :confused:

**Comment by seredat** [comment]
Hi, i am not aware of such possibility. 

Btw, we found your pool, listed.

**Comment by systemroot** [comment]
yes i started! but i'm having a problem with payments 
pool isn't paying miners 
and this is what i get from walletd
```bash
2017-Jun-19 11:46:53.862854 WARNING Requested method not found: transfer
2017-Jun-19 11:47:54.098960 WARNING Requested method not found: getbalance
```

**Comment by seredat** [comment]
Use simplewallet, just create in simplewallet  new wallet with password and run simplewallet in rpc mode. It will work. There is something wrong with network hashrate calculation on pool site, check if you're using correct target interval, ours is 240.

**Comment by systemroot** [comment]
i've start simplewallet as 
```bash
./simplewallet --wallet-file=poolwallet.wallet.backup --password=xxxx --daemon-address=XX.XX.XX.XX:32348 --rpc-bind-ip=127.0.0.1 --rpc-bind-port=699
```
pool is trying to send payments but isn't working and i got those outputs
```bash
2017-Jun-19 12:11:32.873377 DEBUG   Closing connection from 127.0.0.1:58640 total=1
2017-Jun-19 12:12:32.890386 DEBUG   Incoming connection from 127.0.0.1:33068
2017-Jun-19 12:12:32.908195 DEBUG   Closing connection from 127.0.0.1:33068 total=1
```
i was using different wallet before and in "poolwallet.wallet.backup" balance is 0.000 maybe this is the reason?! should i transfer all balance to this so then pool can send payments?!

about stats, i'm trying to find what is wrong pool or web script :confused:

**Comment by seredat** [comment]
Wallet should have balance to be able to send payments. Transfer coins to this wallet. And make sure in pool config is the same address. Also make sure mixin in pool config is set to zero. 

Concering stats make sure you have block target interval 240, not 120 or 60.

**Comment by systemroot** [comment]
stats fixed.

but i can't fix payments..

**Comment by systemroot** [comment]
am i doing wrong something?!

```bash
root@localhost:~# cat test
curl -X POST -i -H "Accept: application/json" -d  '{  
   'params':{  
      'address':'Kge63SffQx55Nqa7qSnMxQDU9Sp6FGRWWM5EShvXn9ayBhBuQXBxAEEDjJKCW96uEuec4ZzgzNBJ1bMtvxepLGvc27PBRjs'
   },
   'jsonrpc':'2.0',
   'id':'test',
   'method':'getBalance'
 }' http://127.0.0.1:691/json_rpc
root@localhost:~# sh test
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 65
Server: CryptoNote-based HTTP server

{"error":{"code":-32700,"message":"Parse error"},"jsonrpc":"2.0"}
root@localhost:~# 
```

`691,` is port where i'm running simplewallet like 
```bash
./simplewallet --wallet-file=poolwallet.wallet.backup --password=xxxxx --daemon-address=46.4.173.213:32348 --rpc-bind-ip=127.0.0.1 --rpc-bind-port=691

**Comment by seredat** [comment]
Refer to this wiki https://github.com/seredat/karbowanec/wiki/Simplewallet-JSON-RPC-API. Try  to change single '  brackets to double "  inside query

**Comment by systemroot** [comment]
```bash
root@node2:~# cat test
curl -X POST -i -H "Accept: application/json" -d  '{  
 	"jsonrpc": "2.0", 
 	"method": "getbalance", 
 	"params": {}
 }' http://127.0.0.1:8888/json_rpc
root@node2:~# sh test
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 81
Server: CryptoNote-based HTTP server

{"jsonrpc":"2.0","result":{"available_balance":24114187898683,"locked_amount":0}}root@node2:~# 
```
well that worket thanks!

**Comment by systemroot** [comment]
@seredat do you know how to save blocks and other stuff which my pool get?
i just did a reboot and all pool blocks, stats, and other stuff have lost...

**Comment by systemroot** [comment]
@seredat is there any update or change or something?!

my pool was running well but i start getting this error 
```bash
"2017-06-22 14:26:52 [pool] (Thread 6) Error polling getblocktemplate {"code":"EADDRNOTAVAIL","errno":"EADDRNOTAVAIL","syscall":"connect"}
2017-06-22 14:26:52 [pool] (Thread 2) Error polling getblocktemplate {"code":"EADDRNOTAVAIL","errno":"EADDRNOTAVAIL","syscall":"connect"}"
```

**Comment by seredat** [comment]
Try restart your daemon

**Comment by systemroot** [comment]
the same error, it works after some time i start to get that error :confounded:

**Comment by systemroot** [comment]
problems solved.
payments fixed..
everything going good now :+1:

**Comment by danycoman** [comment]
i have same error ...`2017-07-18 11:47:49 Error with send_transaction RPC request to wallet daemon {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2017-07-18 11:47:49 Payments failed to send to {"amount":1000000000,"address":"CikrQnEbcyqcnMxP7AxrG2Es1n5gwFr8iQzHKKk5e2dm4pdFaC85SRcHWM6BWUMyL95NDADPxFrJ1DWM336g8mg99kgLZMS"} { amount: 9000000000,
address: 'Cr13DmjPeyw4HvrZJGgnYbBBy3hoXRWyVNQwYKDwiNGRHBDPMZ33gBKF4GXM9vSU83c2TuJwijU5eYVH87wgFa4NDo4zpax' }
2017-07-18 11:48:49 Error with send_transaction RPC request to wallet daemon {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2017-07-18 11:48:49 Payments failed to send to {"amount":1000000000,"address":"CikrQnEbcyqcnMxP7AxrG2Es1n5gwFr8iQzHKKk5e2dm4pdFaC85SRcHWM6BWUMyL95NDADPxFrJ1DWM336g8mg99kgLZMS"} { amount: 9000000000,`

**Comment by danycoman** [comment]
my config

`[Unit]
Description=CharnaCoinWalletRPC
After=network.target

[Service]
User=root
Restart=always
Type=forking
WorkingDirectory=/pool/charnacoin
ExecStart=/pool/charnacoin/charnacoin-wallet-rpc --rpc-bind-port=18091 --wallet-file=daniel2 --password=xxxxxxxx --disable-rpc-login
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
`

**Comment by danycoman** [comment]
Let me fix it , please help.

**Comment by seredat** [comment]
Make sure you're sending rpc requests to correct IP  (in pool's config.json), there should be 127.0.0.1 and the same port your wallet is listening at. It's Monero fork so pool software, config and rpc methods may differ a little. I don't know what's --disable-rpc-login

**Comment by danycoman** [comment]
},

    "daemon": {
        "host": "127.0.0.1",
        "port": 18091
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 18093
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

**Comment by danycoman** [comment]
Do I have to use this command? --disable-rpc-login

**Comment by seredat** [comment]
here 
```
"wallet": {
    "host": "127.0.0.1",
    "port": 18091
},
```

and here 

`ExecStart=/pool/charnacoin/charnacoin-wallet-rpc --rpc-bind-port=18091 --wallet-file=daniel2 --password=xxxxxxxx --disable-rpc-login`

port should be the same. The same goes for the daemon. If you're using default rpc and p2p ports for daemon - fill them in config.json too

**Comment by danycoman** [comment]
it ok now?` "payments": {
        "enabled": true,
        "interval": 60,
        "maxAddresses": 50,
        "mixin": 3,
        "transferFee": 50000000,
        "minPayment": 1000000000,
        "maxTransactionAmount": 10000000000,
        "denomination": 1000000000   
   },

    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 10,
        "poolFee": 1,
        "devDonation": 0.1,
        "coreDevDonation": 0.1,
        "extraFeaturesDevDonation":0.1
    },

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 3,
        "port": 1117,
        "blocks": 30,
        "payments": 30,
        "password": "Password"
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 18091
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 18091
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

    "monitoring": {
        "daemon": {
            "checkInterval": 60,
            "rpcMethod": "getblockcount"
        },
        "wallet": {
            "checkInterval": 60,
            "rpcMethod": "getbalance"
        }
    },

`

**Comment by seredat** [comment]
no, daemon and wallet ports can't be the same

**Comment by danycoman** [comment]
` },

    "daemon": {
        "host": "127.0.0.1",
        "port": 18093
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 18091
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

    "monitoring": {
        "daemon": {
            "checkInterval": 60,
            "rpcMethod": "getblockcount"
**`**

**Comment by seredat** [comment]
in this case run wallet  with 

ExecStart=/pool/charnacoin/charnacoin-wallet-rpc --rpc-bind-port=18091 --wallet-file=daniel2 --password=xxxxxxxx --disable-rpc-login

daemon should be started with rpc port 18093 if it's not your coin's default rpc port.

**Comment by danycoman** [comment]
[Unit]
Description=CharnaCoinWalletRPC
After=network.target

[Service]
User=root
Restart=always
Type=forking
WorkingDirectory=/pool/charnacoin
ExecStart=/pool/charnacoin/charnacoin-wallet-rpc --rpc-bind-port=18091 --wallet-file=daniel2 --password=mypassoword
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

**Comment by danycoman** [comment]
it ok now?

**Comment by seredat** [comment]
yes, try to launch it now

**Comment by danycoman** [comment]
pool is down

**Comment by danycoman** [comment]
i restore configuration pool is up :(

**Comment by seredat** [comment]
don't change pool config, launch wallet with according port

**Comment by danycoman** [comment]
http://mine-pool.ro:1117/admin_log?file=payments_error.log&password=Password

**Comment by danycoman** [comment]
ExecStart=/pool/charnacoin/charnacoin-wallet-rpc --rpc-bind-port=18093 this is daemon ?

or need

ExecStart=/pool/charnacoin/charnacoin-wallet-cli --rpc-bind-port=18093 ?

**Comment by seredat** [comment]
ExecStart=/pool/charnacoin/charnacoin-wallet-cli --rpc-bind-port=18091

daemon it is something like charnacoind - it also has to be running without daemon nor pool nor wallet won't work

**Comment by danycoman** [comment]
charnacoin-blockchain-export  charnacoin-utils-deserialize  charnacoin-wallet-rpc      daniel2              daniel.address.txt  danielwow.address.txt
charnacoin-blockchain-import  charnacoin-wallet-cli         charnacoin-wallet-rpc.log  daniel2.address.txt  daniel.keys         danielwow.keys
charnacoind                   charnacoin-wallet-cli.log     daniel                     daniel2.keys         danielwow           README.md

**Comment by danycoman** [comment]
`[Unit] 
Description=CharnaCoin 
After=network.target 

[Service] 
User=root 
Restart=always 
Type=forking 
ExecStart=/pool/charnacoin/charnacoind --detach 
RemainAfterExit=yes
 
[Install] 
WantedBy=multi-user.target`

**Comment by danycoman** [comment]
I try this command,  ./charnacoind

`2017-07-18 15:23:44.885     7f360d7a7740        INFO    global  src/daemon/main.cpp:282 Charnacoin 'weloobe' (v0.11.0-dc2fe51)
2017-07-18 15:23:44.886     7f360d7a7740        INFO    global  src/daemon/protocol.h:55        Initializing cryptonote protocol...
2017-07-18 15:23:44.886     7f360d7a7740        INFO    global  src/daemon/protocol.h:60        Cryptonote protocol initialized OK
2017-07-18 15:23:44.886     7f360d7a7740        INFO    global  src/daemon/p2p.h:63     Initializing p2p server...
2017-07-18 15:23:44.893     7f360d7a7740        INFO    global  src/daemon/core.h:89    Deinitializing core...
2017-07-18 15:23:44.899     7f360d7a7740        ERROR   daemon  src/daemon/core.h:94    Failed to deinitialize core...
2017-07-18 15:23:44.899     7f360d7a7740        INFO    global  src/daemon/protocol.h:77        Stopping cryptonote protocol...
2017-07-18 15:23:44.899     7f360d7a7740        INFO    global  src/daemon/protocol.h:81        Cryptonote protocol stopped successfully
2017-07-18 15:23:44.899     7f360d7a7740        ERROR   daemon  src/daemon/main.cpp:290 Exception in main! Failed to initialize p2p server.
root@vps:/pool/charnacoin#
`

**Comment by danycoman** [comment]
``
2017-07-18 15:30:39.898     7f19410da740        INFO    global  src/daemon/main.cpp:282 Charnacoin 'weloobe' (v0.11.0-dc2fe51)
2017-07-18 15:30:39.898     7f19410da740        INFO    global  src/daemon/protocol.h:55        Initializing cryptonote protocol...
2017-07-18 15:30:39.898     7f19410da740        INFO    global  src/daemon/protocol.h:60        Cryptonote protocol initialized OK
2017-07-18 15:30:39.898     7f19410da740        INFO    global  src/daemon/p2p.h:63     Initializing p2p server...
2017-07-18 15:30:43.905     7f19410da740        INFO    global  src/daemon/p2p.h:68     P2p server initialized OK
2017-07-18 15:30:43.905     7f19410da740        INFO    global  src/daemon/rpc.h:58     Initializing core rpc server...
2017-07-18 15:30:43.906     7f19410da740        INFO    global  contrib/epee/include/net/http_server_impl_base.h:70     Binding on 127.0.0.1:18091
2017-07-18 15:30:43.906     7f19410da740        INFO    global  src/daemon/rpc.h:63     Core rpc server initialized OK on port: 18091
2017-07-18 15:30:43.906     7f19410da740        INFO    global  src/daemon/core.h:73    Initializing core...
2017-07-18 15:30:43.907     7f19410da740        INFO    global  src/cryptonote_core/cryptonote_core.cpp:328     Loading blockchain from folder /root/.charnacoin/lmdb ...
2017-07-18 15:30:44.011     7f19410da740        INFO    global  src/daemon/core.h:78    Core initialized OK
2017-07-18 15:30:44.011     7f19410da740        INFO    global  src/daemon/rpc.h:68     Starting core rpc server...
2017-07-18 15:30:44.011 [SRV_MAIN]      INFO    global  src/daemon/rpc.h:73     Core rpc server started ok
2017-07-18 15:30:44.012 [SRV_MAIN]      INFO    global  src/daemon/p2p.h:78     Starting p2p net loop...
2017-07-18 15:30:44.014 [P2P1]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:291     [183.80.103.183:60010 INC] Sync data returned a new top block candidate: 50242 -> 50247 [Your node is 5 blocks (0 days) behind]

**Comment by seredat** [comment]
Ok, daemon is running  and syncing :)

**Comment by danycoman** [comment]
Pending Balance: 4800.09675490 CHRC
 Total Paid: 0.00000000 CHRC
 Last Share Submitted: less than a minute ago
 Hash Rate: 309.00 H/sec
 Total Hashes Submitted: 49401466

**Comment by danycoman** [comment]
balance i peiding

**Comment by danycoman** [comment]
i try this command

`root@vps:/pool/charnacoin# ./charnacoin-wallet-rpc  --rpc-bind-port 18093
2017-07-18 15:42:22.112     7f5464dc6740        INFO    global  contrib/epee/src/mlog.cpp:145   New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,stacktrace:INFO
Charnacoin 'weloobe' (v0.11.0-dc2fe51)
Logging to ./charnacoin-wallet-rpc.log
2017-07-18 15:42:22.112     7f5464dc6740        ERROR   wallet.rpc      src/wallet/wallet_rpc_server.cpp:1526   Must specify --wallet-file or --generate-from-json
root@vps:/pool/charnacoin#
`

**Comment by seredat** [comment]
gee, run full command. it says to you to specify wallet file, like this

charnacoin-wallet-rpc --rpc-bind-port=18091 --wallet-file=daniel2 --password=xxxxxxxx --disable-rpc-login

**Comment by danycoman** [comment]
-bash: !@#: event not found

**Comment by danycoman** [comment]
My password contains characters @#$%%^&*

**Comment by danycoman** [comment]
change the password  wallet file and try command  and result 

2017-07-18 16:18:58.917     7fd1392d0740        WARN    wallet.rpc      src/wallet/wallet_rpc_server.cpp:1530   Loading wallet...
2017-07-18 16:18:58.922     7fd1392d0740        ERROR   msgwriter       src/common/scoped_message_writer.h:94   Error: the password file specified could not be read

**Comment by seredat** [comment]
Create new wallet with password without special characters, change it's address in pool's config.json  then

**Comment by danycoman** [comment]
seredat , 


i not have this folder **src/wallet/**wallet_rpc_server.cpp:1530

**Comment by seredat** [comment]
No, these are just verbose Monero errors for debugging purposes, just do as I suggest.

**Comment by systemroot** [comment]
just asking

whats the point of mining `charnacoin` ?! i searched some online doesn't seems to listen even on marketcap. are they supported by any shop?

**Comment by danycoman** [comment]
2017-07-18 16:34:21.113     7f982e0da740        WARN    wallet.rpc      src/wallet/wallet_rpc_server.cpp:1530   Loading wallet...
2017-07-18 16:34:21.116     7f982e0da740        ERROR   msgwriter       src/common/scoped_message_writer.h:94   Error: the password file specified could not be read

**Comment by danycoman** [comment]
root@vps:/pool/charnacoin# killall charnacoin-wallet-rpc
charnacoin-wallet-rpc: no process found

yes charnacoin-wallet-rpc no process

**Comment by danycoman** [comment]
SystemRoot,

https://charnacoin.com/
www.mine-pool.ro- my pool
http://chrc.m42.cx/ -2
https://charnacoin.com:435/
https://cryptodao.com/site/index/CHRC
https://gitter.im/charnacrypto/charnacoin

**Comment by seredat** [comment]
Guys, disscuss this at forum please :)

**Comment by seredat** [comment]
fine, if you restart your pool it should mine to your new address and make payout.

**Comment by danycoman** [comment]
Need  create new adrees?  Can not update transactions? And pay miner?

**Comment by danycoman** [comment]
Daemon
Last check: less than a minute ago
Last status: ok
Last response:
{"count":50306,"status":"OK"}
Last fail: about an hour ago
Last fail response:
{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
Wallet
Last check: less than a minute ago
Last status: fail
Last response:
{}
Last fail: less than a minute ago
Last fail response:
{}

**Comment by seredat** [comment]
apparently daemon is running on default p2p and rpc port, find out what's your coin's default rpc port and change it in pool's config.json

**Comment by danycoman** [comment]
``Logging to ./charnacoin-wallet-rpc.log
2017-07-18 17:34:47.661     7faa954c6740        WARN    wallet.rpc      src/wallet/wallet_rpc_server.cpp:1530   Loading wallet...
2017-07-18 17:34:47.738     7faa954c6740        WARN    wallet.wallet2  src/wallet/wallet2.cpp:2413     Loaded wallet keys file, with public address: CnB4UQK4WxxK9agMuNwB8VabKWBDwr1jWc1ExHUcE7N1h76pMERJeVKF2gMLZ6WECs3wrPBd1recZWvVVXaHCQQW5dwjuSQ
2017-07-18 17:34:48.351     7faa954c6740        WARN    wallet.rpc      src/wallet/wallet_rpc_server.cpp:174    RPC username/password is stored in file charnacoin-wallet-rpc.28028.login
2017-07-18 17:34:48.351     7faa954c6740        INFO    global  contrib/epee/include/net/http_server_impl_base.h:70     Binding on 127.0.0.1:28028
2017-07-18 17:34:48.352     7faa954c6740        WARN    wallet.rpc      src/wallet/wallet_rpc_server.cpp:1573   Starting wallet rpc server

**Comment by danycoman** [comment]
[Unit]
Description=CharnaCoinWalletRPC
After=network.target

[Service]
User=root
Restart=always
Type=forking
WorkingDirectory=/pool/charnacoin
ExecStart=/pool/charnacoin/charnacoin-wallet-rpc --rpc-bind-port=28028 --wallet-file=pool --password=mypassword
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

**Comment by danycoman** [comment]
"daemon": {
        "host": "127.0.0.1",
        "port": 18091
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 28028
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

**Comment by danycoman** [comment]
it ok?

**Comment by seredat** [comment]
Yes, since 18091 is default daemon's rpc port for wallet you should use another one, now it should work

**Comment by danycoman** [comment]
I think the wallet is actually defective ...
I've manually tried to send

transfer 0 Cr13DmjPeyw4HvrZJGgnYbBBy3hoXRWyVNQwYKDwiNGRHBDPMZ33                                                                                                                     gBKF4GXM9vSU83c2TuJwijU5eYVH87wgFa4NDo4zpax 4800
Error: unexpected error: Error! What is c if cols = 1!

**Comment by seredat** [comment]
Maybe you should ask dev.

**Comment by danycoman** [comment]
yes i talk dev.. thanks seredat

**Comment by systemroot** [comment]
@seredat what do u think about this?
![image](https://user-images.githubusercontent.com/19308979/28648665-edd23f5a-725e-11e7-8d15-f6bcd876704a.png)

7days no block! (hash rate has been 1-1.5KH/s all the time 1Day age went 300-400H/s because i moved some workers. because i wasn't getting any block
look at the blocks https://krb.sick.al/#pool_blocks . everything was going well then idk what happen! 
is this just because krb world hash rate went too big those days?!

**Comment by seredat** [comment]
I think it could be just big hashrate. We have incursions of big miners.

**Comment by aivve** [comment]
You should choose port 7777 or 8888. Besides, that particular pool is overcrowded, consider switching to other pool.

**Comment by theraw** [comment]
@aivve thank you, I'm on port 7777 now. there are some disconnects but it's better than before.

Thanks for your suggestion but i will stay on official pool as of now. i'm done with other pools getting `1KRB` max `2KRB` **/day** with `3-5KH/s` that's a joke!. 
i got 1.1KRB in official pool just in 1-2/hours
