### ISSUE TITLE
QXcbConnection

### ISSUE THREAD

**Issue by ABILATA** [seredat/karbowanec#52]
Dear, 

I compiled the karbowallet and when I try to run the ./karbowanec file I got the following outcome:
./karbowanec
QXcbConnection: Could not connect to display 
Aborted (core dumped)

Thank you in advance for your help, kind regards

**Comment by aivve** [comment]
It's strange. Try `export DISPLAY=:0` then run wallet

**Comment by ABILATA** [comment]
I still got the same outcome: 
~/karbowanecwallet/build$ ./karbowanec
QXcbConnection: Could not connect to display :0
Aborted (core dumped)

**Comment by aivve** [comment]
Is it some remote access? Or maybe it's root? Try `export DISPLAY=:0.0`

**Comment by ABILATA** [comment]
Thank you for your promptness and sorry for my delayed anwer. Yes, it is a remote access, I am doing it in a ubuntu server. Before I could test your suggestion I reinstalled the server (for a different reason) and started everything again. Unfortunatelly now I have a different problem: 
karbowanecwallet-Sudo/src/AddressProvider.cpp:7:10: fatal error: QJsonArray: No such file or directory
 #include <QJsonArray>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/karbowanec.dir/build.make:249: recipe for target 'CMakeFiles/karbowanec.dir/src/AddressProvider.cpp.o' failed
make[2]: *** [CMakeFiles/karbowanec.dir/src/AddressProvider.cpp.o] Error 1
CMakeFiles/Makefile2:181: recipe for target 'CMakeFiles/karbowanec.dir/all' failed
make[1]: *** [CMakeFiles/karbowanec.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by aivve** [comment]
You need to fix your QT installation.

**Comment by ABILATA** [comment]
Indeed, that is like hell to solve for unexperienced people like me. Still trying...
