### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by nathjyo** [seredat/karbowanec#58]
hi my build gets to 94% then fails not sure what the issue is, any help would be appreciated 
![screen shot 2018-08-15 at 10 45 26 pm](https://user-images.githubusercontent.com/37133338/44148852-3ce5dca2-a0dd-11e8-9f1d-2d0b291c9b54.png)

**Comment by aivve** [comment]
Maybe os and boost version specific? 🤔

**Comment by nathjyo** [comment]
thanks ill have a look

**Comment by nathjyo** [comment]
Changed to correct boost version and os version still same issue 😞

**Comment by g1itch** [comment]
@nathjyo do you have boost context and static libs installed? karbo uses it.
