### ISSUE TITLE
how do the block upgrades work?

### ISSUE THREAD

**Issue by lukasgolson** [seredat/karbowanec#6]
hello!

Just a quick question on how the block upgrades (for example from V1 to V2 work!)

I am the developer on another cryptonote based coin (PalladiumCoin) and we are having troubles implementing said feature!

Thanks,
lukasdragon

**Comment by seredat** [comment]
Hello,

There's code for that in newer versions of Bytecoin. My advise is to use Bytecoin or Forknote as a basis instead of reference Cryptonote code - it's buggy.

**Comment by lukasgolson** [comment]
thanks for your quick reply!

Unfortunately the coin has already launched so I don't think that would be completely feasible :(

**Comment by seredat** [comment]
We also upgraded from reference CN to newer Bytecoin code, so it's possible.

**Comment by lukasgolson** [comment]
that's good to know, we will try our hand at it in a couple of days!

**Comment by QuinnMallorry** [comment]
how did it go?

**Comment by lukasgolson** [comment]
we skipped the block upgrades, and just implemented the new difficulty algo after a block checkpoint. 
We are doing research on block upgrades and should have something working in about a week!

**Comment by QuinnMallorry** [comment]
awesome, I'll keep an eye out for the code
