### ISSUE TITLE
MixIn count is too big error on walletd

### ISSUE THREAD

**Issue by ns1000** [seredat/karbowanec#61]
Since the new release I am getting 
"MixIn count is too big" errors when trying to send KRB's
I already tried:
Resetting the wallet.
Optimizing all outputs with fusion transactions.

In simplewallet it does work with the same address.

**Comment by aivve** [comment]
Thanks for notifying us, we will try to investigate.

**Comment by aivve** [comment]
Thanks for notifying us, we will try to investigate.

**Comment by aivve** [comment]
Fixed in https://github.com/seredat/karbowanec/commit/8b50246daf760767dd73abd4d95dd812e577aad2
