### ISSUE TITLE
PaymentGateway doesn't sync in latest release 1.5.7

### ISSUE THREAD

**Issue by g1itch** [seredat/karbowanec#62]
Hello!

After update to 1.5.7 PaymentGateway started to hang during synchronization and eats 100% CPU (one core). Synchronized successfully after downgrade to 1.5.6.

**Comment by aivve** [comment]
It would help if you send us some logs if possible.
Also please try to use compiled from latest sources.

**Comment by g1itch** [comment]
Unfortunately I cannot reproduce it anymore ):
