### ISSUE TITLE
build error on FreeBSD 11

### ISSUE THREAD

**Issue by bogdartysh** [seredat/karbowanec#66]
When building on FreeBSD: 
`make > make.out`
build failed, output attached
[make.zip](https://github.com/seredat/karbowanec/files/2634751/make.zip)

cmake version is 3.12.2
boost-all 1.68
boost_build 2.0

**Comment by bogdartysh** [comment]
[make.zip](https://github.com/seredat/karbowanec/files/2636058/make.zip)

**Comment by aivve** [comment]
Thanks for alerting us. I am not sure it builds on FreeBSD at all and I never tried. I can't open the archive so can't even look at the errors.

**Comment by bogdartysh** [comment]
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- Building without build tag
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
CMake Warning (dev) at CMakeLists.txt:99 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Building for a 64-bit system
-- Building internal libraries as static
-- Building on amd64 for native
-- AES support enabled
-- Found Boost Version: 106800
CMake Warning at src/version.cmake:3 (message):
  Cannot determine current revision.  Make sure that you are building either
  from a Git working tree or from a source archive.
Call Stack (most recent call first):
  CMakeLists.txt:544 (include)


-- Found Git: /usr/local/bin/git
CMake Warning in CMakeLists.txt:
  CMAKE_SKIP_INSTALL_RULES was enabled even though installation rules have
  been specified


-- Configuring done
-- Generating done
-- Build files have been written to: /root/personal/karbowanec-master/karbowanec-master/build/release
cd build/release && make
fatal: not a git repository (or any of the parent directories): .git
CMake Warning at src/version.cmake:3 (message):
  Cannot determine current revision.  Make sure that you are building either
  from a Git working tree or from a source archive.


[  0%] Built target version
[  1%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/connecthostport.c.o
/root/personal/karbowanec-master/karbowanec-master/external/miniupnpc/connecthostport.c:155:2: warning: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)' [-Wimplicit-function-declaration]
        snprintf(port_str, sizeof(port_str), "%hu", port);
        ^
/root/personal/karbowanec-master/karbowanec-master/external/miniupnpc/connecthostport.c:155:2: note: include the header <stdio.h> or explicitly provide a declaration for 'snprintf'
/root/personal/karbowanec-master/karbowanec-master/external/miniupnpc/connecthostport.c:191:9: error: incomplete definition of type 'struct sockaddr_in6'
                        addr6->sin6_scope_id = scope_id;
                        ~~~~~^
/root/personal/karbowanec-master/karbowanec-master/external/miniupnpc/connecthostport.c:190:11: note: forward declaration of 'struct sockaddr_in6'
                        struct sockaddr_in6 * addr6 = (struct sockaddr_in6 *)p->ai_addr;
                               ^
1 warning and 1 error generated.
*** Error code 1

Stop.
make[3]: stopped in /root/personal/karbowanec-master/karbowanec-master/build/release
*** Error code 1

Stop.
make[2]: stopped in /root/personal/karbowanec-master/karbowanec-master/build/release
*** Error code 1

Stop.
make[1]: stopped in /root/personal/karbowanec-master/karbowanec-master/build/release
*** Error code 1

Stop.
make: stopped in /root/personal/karbowanec-master/karbowanec-master

**Comment by aivve** [comment]
Use these binaries until we merge necessary fixes https://github.com/seredat/karbowanec/releases/download/v.1.6.2/karbowanec-1.6.2_freebsd-11_x86_64.zip

**Comment by bogdartysh** [comment]
@aivve : prov
