### ISSUE TITLE
Неправильный баланс кошелька RPC Wallet

### ISSUE THREAD

**Issue by parmax** [seredat/karbowanec#77]
Я создал кошель с ключом только для просмотра.
Когда хочу просмотреть баланс на кошельке, то получаю неправильный баланс:
curl --data-binary '{"params":{},"jsonrpc":"2.0","id":"test","method":"getBalance"}' http://127.0.0.1:8070/json_rpc
{"id":"test","jsonrpc":"2.0","result":{"availableBalance":239904970012039,"lockedAmount":0}
А кошель на компе говорит что реально доступно 138.753070012039 крб.
Вопрос это из-за того что ключ только на просмотр или ошибка в работе кошелька RPC Wallet.

**Comment by aivve** [comment]
"Not a bug".

**Comment by aivve** [comment]
Да, это потому что кошелек просмотра не видит исходящих транзакций, соотвественно он не может правильно посчитать баланс.
